name: build

on: push

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build libsdl2-dev

      - name: Build-Debug
        run: |
          mkdir build-debug
          cd build-debug
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          ninja

      - name: Build-Release
        run: |
          mkdir build-release
          cd build-release
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja

  Windows:
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-devel-2.26.3-VC.zip" -OutFile "SDL2-devel-2.26.3-VC.zip"
          Expand-Archive -Path SDL2-devel-2.26.3-VC.zip
          echo "SDL2_DIR=$(pwd)\SDL2-devel-2.26.3-VC\SDL2-2.26.3\" >>${env:GITHUB_ENV}

      - name: Build-Debug
        shell: cmd
        run: |
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build-debug
          cd build-debug
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
          nmake

      - name: Build-Release
        shell: cmd
        run: |
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build-release
          cd build-release
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          nmake
