name: build

on: push

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build libsdl2-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
